// 0: Name
// 1: Risk Level
// 2: Qliphoth Counter: -1 = X
// 3: Max Enkephalin: -1 = X
// 4: Capable of Breach
// 5: Image path to abnormality portrait
const abnoList: [string, string, number, number, boolean, string][] = [
  ["Standard Training-Dummy Rabbit", "Teth", 1, 10, true, "abnoimages/TrainingRabbit.webp"],
  ["Scorched Girl", "Teth", 2, 12, true, "abnoimages/ScorchedGirl.webp"],
  ["One Sin and Hundreds of Good Deeds", "Zayin", -1, 10, false, "abnoimages/OneSin.webp"],
  ["The Queen of Hatred", "Waw", 2, 22, true, "abnoimages/QueenOfHatred.webp"],
  ["Happy Teddy Bear", "He", -1, 15, false, "abnoimages/HappyTeddyBear.webp"],
  ["Red Shoes", "He", 1, 16, false, "abnoimages/RedShoes.webp"],
  ["Old Lady", "Teth", 4, 14, false, "abnoimages/OldLady.webp"],
  ["Nameless Fetus", "He", 1, 18, false, "abnoimages/NamelessFetus.webp"],
  ["The Lady Facing the Wall", "Teth", 2, 14, false, "abnoimages/LadyFacingTheWall.webp"],
  ["Nothing There", "Aleph", 1, 33, true, "abnoimages/NothingThere.webp"],
  ["1.76 MHz", "Teth", 4, 12, true, "abnoimages/MHz.webp"],
  ["Singing Machine", "He", 1, 18, false, "abnoimages/SingingMachine.webp"],
  ["The Silent Orchestra", "Aleph", 2, 30, true, "abnoimages/SilentOrchestra.webp"],
  ["Warm-Hearted Woodsman", "He", 1, 18, false, "abnoimages/WarmHeartedWoodsman.webp"],
  ["The Snow Queen", "He", -1, 18, false, "abnoimages/SnowQueen.webp"],
  ["Big Bird", "Waw", 5, 20, true, "abnoimages/BigBird.webp"],
  ["All-Around Helper", "He", 2, 16, true, "abnoimages/Helper.webp"],
  ["Snow White's Apple", "Waw", 1, 20, true, "abnoimages/Apple.webp"],
  ["Spider Bud", "Teth", -1, 14, false, "abnoimages/SpiderBud.webp"],
  ["Beauty and the Beast", "Teth", -1, 12, false, "abnoimages/Beauty.webp"],
  ["Plague Doctor", "Zayin", 1, 10, false, "abnoimages/PlagueDoctor.webp"],
  ["WhiteNight", "Aleph", 3, 35, true, "abnoimages/WhiteNight.webp"],
  ["Don't Touch Me", "Zayin", -1, -1, false, "abnoimages/Don'tTouch.webp"],
  ["Rudolta of the Sleigh", "He", 2, 18, true, "abnoimages/Rudolta.webp"],
  ["Queen Bee", "Waw", 1, 22, false, "abnoimages/QueenBee.webp"],
  ["Bloodbath", "Teth", -1, 14, false, "abnoimages/Bloodbath.webp"],
  ["Opened Can of WellCheers", "Zayin", -1, 10, false, "abnoimages/Wellcheers.webp"],
  ["Alriune", "Waw", 1, 22, true, "abnoimages/Alriune.webp"],
  ["Forsaken Murderer", "Teth", 1, 14, true, "abnoimages/ForsakenMurderer.webp"],
  ["Child of the Galaxy", "He", 5, 16, false, "abnoimages/ChildOfGalaxy.webp"],
  ["Punishing Bird", "Teth", 4, 12, true, "abnoimages/PunishingBird.webp"],
  ["Little Red Riding Hooded Mercenary", "Waw", 3, 20, true, "abnoimages/LittleRed.webp"],
  ["Big and Will be Bad Wolf", "Waw", 2, 22, true, "abnoimages/BadWolf.webp"],
  ["Fragment of the Universe", "Teth", 2, 12, true, "abnoimages/FragmentUniverse.webp"],
  ["Crumbling Armor", "Teth", -1, 12, false, "abnoimages/CrumblingArmor.webp"],
  ["Judgement Bird", "Waw", 2, 24, true, "abnoimages/JudgementBird.webp",],
  ["Apocalypse Bird", "Aleph", -1, 12, true, "abnoimages/ApocalypseBird.webp"],
  ["The King of Greed", "Waw", 1, 22, true, "abnoimages/KingOfGreed.webp"],
  ["The Little Prince", "Waw", 2, 24, false, "abnoimages/LittlePrince.webp"],
  ["Laetitia", "He", -1, 16, false, "abnoimages/Laetitia.webp"],
  ["Funeral of the Dead Butterflies", "He", 2, 16, true, "abnoimages/DeadButterflies.webp"],
  ["Der Freischütz", "He", 3, 18, false, "abnoimages/Der.webp"],
  ["Dream of a Black Swan", "Waw", 5, 24, true, "abnoimages/BlackSwan.webp"],
  ["The Dreaming Current", "Waw", 2, 20, true, "abnoimages/DreamingCurrent.webp"],
  ["The Burrowing Heaven", "Waw", 3, 24, true, "abnoimages/BurrowingHeaven.webp"],
  ["The Knight of Despair", "Waw", -1, 22, true, "abnoimages/KnightOfDespair.webp"],
  ["The Naked Nest", "Waw", -1, 22, false, "abnoimages/NakedNest.webp"],
  ["The Mountain of Smiling Bodies", "Aleph", 2, 30, true, "abnoimages/SmilingBodies.webp"],
  ["Schadenfreude", "He", 2, 18, true, "abnoimages/Schadenfreude.webp"],
  ["Fairy Festival", "Zayin", -1, 10, false, "abnoimages/FairyFestival.webp"],
  ["Meat Lantern", "Teth", 1, 14, true, "abnoimages/MeatLantern.webp"],
  ["Scarecrow Searching for Wisdom", "He", 1, 18, true, "abnoimages/Scarecrow.webp"],
  ["Dimensional Refraction Variant", "Waw", 2, 22, true, "abnoimages/Variant.webp"],
  ["CENSORED", "Aleph", 2, 32, true, "abnoimages/CENSORED.webp"],
  ["Today's Shy Look", "Teth", -1, 12, false, "abnoimages/ShyLook.webp"],
  ["Blue Star", "Aleph", 2, 33, true, "abnoimages/BlueStar.webp"],
  ["Porccubus", "He", 2, 18, true, "abnoimages/Porccubus.webp"],
  ["Void Dream", "Teth", 2, 14, true, "abnoimages/VoidDream.webp"],
  ["Grave of Cherry Blossoms", "Teth", 3, 12, false, "abnoimages/CherryBlossoms.webp"],
  ["The Firebird", "Waw", 3, 24, true, "abnoimages/Firebird.webp"],
  ["Yin", "Waw", 2, 20, true, "abnoimages/Yin.webp"],
  ["Il Pianto della Luna", "Waw", 3, 20, true, "abnoimages/Luna.webp"],
  ["Army in Black", "Aleph", 3, 30, true, "abnoimages/ArmyInBlack.webp"],
  ["Ppodae", "Teth", 2, 12, true, "abnoimages/Ppodae.webp"],
  ["Parasite Tree", "Waw", 1, 24, false, "abnoimages/ParasiteTree.webp"],
  ["Melting Love", "Aleph", 3, 32, true, "abnoimages/MeltingLove.webp"],
  ["Clouded Monk", "Waw", 3, 22, true, "abnoimages/CloudedMonk.webp"],
  ["You're Bald", "Zayin", -1, 6, false, "abnoimages/Bald.webp"]
];

const abnoNameList = ["Standard Training-Dummy Rabbit", "Scorched Girl", "One Sin and Hundreds of Good Deeds", "The Queen of Hatred", "Happy Teddy Bear", "Red Shoes", "Old Lady", "Nameless Fetus",
  "The Lady Facing the Wall", "Nothing There", "1.76 MHz", "Singing Machine", "The Silent Orchestra", "Warm-Hearted Woodsman", "The Snow Queen", "Big Bird", "All-Around Helper",
  "Snow White's Apple", "Spider Bud", "Beauty and the Beast", "Plague Doctor", "WhiteNight", "Don't Touch Me", "Rudolta of the Sleigh", "Queen Bee", "Bloodbath", "Opened Can of WellCheers",
  "Alriune", "Forsaken Murderer", "Child of the Galaxy", "Punishing Bird", "Little Red Riding Hooded Mercenary", "Big and Will be Bad Wolf", "Fragment of the Universe",
  "Crumbling Armor", "Judgement Bird", "Apocalypse Bird", "The King of Greed", "The Little Prince", "Laetitia", "Funeral of the Dead Butterflies", "Der Freischütz", "Dream of a Black Swan",
  "The Dreaming Current", "The Burrowing Heaven", "The Knight of Despair", "The Naked Nest", "The Mountain of Smiling Bodies", "Schadenfreude", "Fairy Festival", "Meat Lantern", "Scarecrow Searching for Wisdom",
  "Dimensional Refraction Variant", "CENSORED", "Today's Shy Look", "Blue Star", "Porccubus", "Void Dream", "Grave of Cherry Blossoms", "The Firebird", "Yin",
  "Il Pianto della Luna", "Army in Black", "Ppodae", "Parasite Tree", "Melting Love", "Clouded Monk", "You're Bald"];

export { abnoNameList };
export default abnoList;